name: build_test_react
run-name: ${{ github.actor }} is trying to build the application
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install project
        run: yarn install
      - name: Build the project
        run: yarn run build --if-present    
        