name: learn-github-actions
run-name: ${{ github.actor }} is trying to run a script
on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: run script file
        run: chmod +x ./run.sh && ./run.sh
        shell: bash
      - name: Print Secret
        env:
          SUPERSECRETNUMBER: ${{ secrets.SUPERSECRETNUMBER }}
        run: echo $SUPERSECRETNUMBER