name: learn-github-actions
run-name: ${{ github.actor }} is trying to run a script
on: [push]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - uses: actions/checkout@v4
      - name: run script file
        run: chmod +x run.sh && ./run.sh
        shell: bash